### ISSUE TITLE
[Refactor] User를 리팩토링해라

### ISSUE THREAD

**Issue by M-ung** [MoodBuddy/Server#12]
## ⚒️ Issue
2차 개발을 위해 코드 리팩토링해야 함.

## 📝 To-do
- [ ] User 퍼사드 패턴 적용
- [ ] DTO를 record로 변경
- [ ] mapstruct 적용
- [ ] 불필요한 API 제거
- [ ] of, from 메서드 활용
