### ISSUE TITLE
[Refactor]  Diary & BookMark를 리팩토링해라

### ISSUE THREAD

**Issue by M-ung** [MoodBuddy/Server#8]
## ⚒️ Issue
2차 개발을 위해 코드 리팩토링해야 함.

## 📝 To-do
- [x] Diary 퍼사드 패턴 적용
- [x] BookMark 퍼사드 패턴 적용
- [x] DTO를 record로 변경
- [x] mapstruct 적용
- [x] 불필요한 API 제거
- [x] of, from 메서드 활용
